export const velhoTestamento = [
  { id: 1, nome: "genesis", titulo: "Gênesis", capitulos: 50 },
  { id: 2, nome: "exodo", titulo: "Êxodo", capitulos: 40 },
  { id: 3, nome: "levitico", titulo: "Levítico", capitulos: 27 },
  { id: 4, nome: "numeros", titulo: "Números", capitulos: 36 },
  { id: 5, nome: "deuteronomio", titulo: "Deuteronômio", capitulos: 34 },
  { id: 6, nome: "josue", titulo: "Josué", capitulos: 24 },
  { id: 7, nome: "juizes", titulo: "Juízes", capitulos: 21 },
  { id: 8, nome: "rute", titulo: "Rute", capitulos: 4 },
  { id: 9, nome: "1samuel", titulo: "1 Samuel", capitulos: 31 },
  { id: 10, nome: "2samuel", titulo: "2 Samuel", capitulos: 24 },
  { id: 11, nome: "1reis", titulo: "1 Reis", capitulos: 22 },
  { id: 12, nome: "2reis", titulo: "2 Reis", capitulos: 25 },
  { id: 13, nome: "1cronica", titulo: "1 Crônicas", capitulos: 29 },
  { id: 14, nome: "2cronicas", titulo: "2 Crônicas", capitulos: 36 },
  { id: 15, nome: "esdras", titulo: "Esdras", capitulos: 10 },
  { id: 16, nome: "neemias", titulo: "Neemias", capitulos: 13 },
  { id: 17, nome: "ester", titulo: "Ester", capitulos: 10 },
  { id: 18, nome: "jo", titulo: "Jó", capitulos: 42 },
  { id: 19, nome: "salmos", titulo: "Salmos", capitulos: 150 },
  { id: 20, nome: "proverbios", titulo: "Provérbios", capitulos: 31 },
  { id: 21, nome: "eclesiastes", titulo: "Eclesiastes", capitulos: 12 },
  { id: 22, nome: "canticos", titulo: "Cânticos", capitulos: 8 },
  { id: 23, nome: "isaias", titulo: "Isaías", capitulos: 66 },
  { id: 24, nome: "jeremias", titulo: "Jeremias", capitulos: 52 },
  { id: 25, nome: "lamentacoes", titulo: "Lamentações", capitulos: 5 },
  { id: 26, nome: "ezequiel", titulo: "Ezequiel", capitulos: 48 },
  { id: 27, nome: "daniel", titulo: "Daniel", capitulos: 12 },
  { id: 28, nome: "oseias", titulo: "Oséias", capitulos: 14 },
  { id: 29, nome: "joel", titulo: "Joel", capitulos: 3 },
  { id: 30, nome: "amos", titulo: "Amós", capitulos: 9 },
  { id: 31, nome: "obadias", titulo: "Obadias", capitulos: 1 },
  { id: 32, nome: "jonas", titulo: "Jonas", capitulos: 4 },
  { id: 33, nome: "miqueias", titulo: "Miqueias", capitulos: 7 },
  { id: 34, nome: "naum", titulo: "Naum", capitulos: 3 },
  { id: 35, nome: "habacuque", titulo: "Habacuque", capitulos: 3 },
  { id: 36, nome: "sofonias", titulo: "Sofonias", capitulos: 3 },
  { id: 37, nome: "ageu", titulo: "Ageu", capitulos: 2 },
  { id: 38, nome: "zacarias", titulo: "Zacarias", capitulos: 14 },
  { id: 39, nome: "malaquias", titulo: "Malaquias", capitulos: 4 }
];

export const novoTestamento = [
  { id: 40, nome: "mateus", titulo: "Mateus", capitulos: 28 },
  { id: 41, nome: "marcos", titulo: "Marcos", capitulos: 16 },
  { id: 42, nome: "lucas", titulo: "Lucas", capitulos: 24 },
  { id: 43, nome: "joao", titulo: "João", capitulos: 21 },
  { id: 44, nome: "atos", titulo: "Atos", capitulos: 28 },
  { id: 45, nome: "romanos", titulo: "Romanos", capitulos: 16 },
  { id: 46, nome: "1corintios", titulo: "1 Coríntios", capitulos: 16 },
  { id: 47, nome: "2corintios", titulo: "2 Coríntios", capitulos: 13 },
  { id: 48, nome: "galatas", titulo: "Gálatas", capitulos: 6 },
  { id: 49, nome: "efesios", titulo: "Efésios", capitulos: 6 },
  { id: 50, nome: "filipenses", titulo: "Filipenses", capitulos: 4 },
  { id: 51, nome: "colossenses", titulo: "Colossenses", capitulos: 4 },
  { id: 52, nome: "1tessalonicenses", titulo: "1 Tessalonicenses", capitulos: 5 },
  { id: 53, nome: "2tessalonicenses", titulo: "2 Tessalonicenses", capitulos: 3 },
  { id: 54, nome: "1timoteo", titulo: "1 Timóteo", capitulos: 6 },
  { id: 55, nome: "2timoteo", titulo: "2 Timóteo", capitulos: 4 },
  { id: 56, nome: "tito", titulo: "Tito", capitulos: 3 },
  { id: 57, nome: "filemon", titulo: "Filemom", capitulos: 1 },
  { id: 58, nome: "hebreus", titulo: "Hebreus", capitulos: 13 },
  { id: 59, nome: "tiago", titulo: "Tiago", capitulos: 5 },
  { id: 60, nome: "1pedro", titulo: "1 Pedro", capitulos: 5 },
  { id: 61, nome: "2pedro", titulo: "2 Pedro", capitulos: 3 },
  { id: 62, nome: "1joao", titulo: "1 João", capitulos: 5 },
  { id: 63, nome: "2joao", titulo: "2 João", capitulos: 1 },
  { id: 64, nome: "3joao", titulo: "3 João", capitulos: 1 },
  { id: 65, nome: "judas", titulo: "Judas", capitulos: 1 },
  { id: 66, nome: "apocalipse", titulo: "Apocalipse", capitulos: 22 }
];
