export const velhoTestamento = [
  { nome: "genesis", titulo: "Gênesis" },
  { nome: "exodo", titulo: "Êxodo" },
  { nome: "levitico", titulo: "Levítico" },
  { nome: "numeros", titulo: "Números" },
  { nome: "deuteronomio", titulo: "Deuteronômio" },
  { nome: "josue", titulo: "Josué" },
  { nome: "juizes", titulo: "Juízes" },
  { nome: "rute", titulo: "Rute" },
  { nome: "1samuel", titulo: "1 Samuel" },
  { nome: "2samuel", titulo: "2 Samuel" },
  { nome: "1reis", titulo: "1 Reis" },
  { nome: "2reis", titulo: "2 Reis" },
  { nome: "1cronica", titulo: "1 Crônicas" },
  { nome: "2cronicas", titulo: "2 Crônicas" },
  { nome: "esdras", titulo: "Esdras" },
  { nome: "neemias", titulo: "Neemias" },
  { nome: "ester", titulo: "Ester" },
  { nome: "jo", titulo: "Jó" },
  { nome: "salmos", titulo: "Salmos" },
  { nome: "proverbios", titulo: "Provérbios" },
  { nome: "eclesiastes", titulo: "Eclesiastes" },
  { nome: "canticos", titulo: "Cânticos" },
  { nome: "isaias", titulo: "Isaías" },
  { nome: "jeremias", titulo: "Jeremias" },
  { nome: "lamentacoes", titulo: "Lamentações" },
  { nome: "ezequiel", titulo: "Ezequiel" },
  { nome: "daniel", titulo: "Daniel" },
  { nome: "oseias", titulo: "Oséias" },
  { nome: "joel", titulo: "Joel" },
  { nome: "amos", titulo: "Amós" },
  { nome: "obadias", titulo: "Obadias" },
  { nome: "jonas", titulo: "Jonas" },
  { nome: "miqueias", titulo: "Miqueias" },
  { nome: "naum", titulo: "Naum" },
  { nome: "habacuque", titulo: "Habacuque" },
  { nome: "sofonias", titulo: "Sofonias" },
  { nome: "ageu", titulo: "Ageu" },
  { nome: "zacarias", titulo: "Zacarias" },
  { nome: "malaquias", titulo: "Malaquias" }
];

export const novoTestamento = [
  { nome: "mateus", titulo: "Mateus" },
  { nome: "marcos", titulo: "Marcos" },
  { nome: "lucas", titulo: "Lucas" },
  { nome: "joao", titulo: "João" },
  { nome: "atos", titulo: "Atos" },
  { nome: "romanos", titulo: "Romanos" },
  { nome: "1corintios", titulo: "1 Coríntios" },
  { nome: "2corintios", titulo: "2 Coríntios" },
  { nome: "galatas", titulo: "Gálatas" },
  { nome: "efesios", titulo: "Efésios" },
  { nome: "filipenses", titulo: "Filipenses" },
  { nome: "colossenses", titulo: "Colossenses" },
  { nome: "1tessalonicenses", titulo: "1 Tessalonicenses" },
  { nome: "2tessalonicenses", titulo: "2 Tessalonicenses" },
  { nome: "1timoteo", titulo: "1 Timóteo" },
  { nome: "2timoteo", titulo: "2 Timóteo" },
  { nome: "tito", titulo: "Tito" },
  { nome: "filemon", titulo: "Filemom" },
  { nome: "hebreus", titulo: "Hebreus" },
  { nome: "tiago", titulo: "Tiago" },
  { nome: "1pedro", titulo: "1 Pedro" },
  { nome: "2pedro", titulo: "2 Pedro" },
  { nome: "1joao", titulo: "1 João" },
  { nome: "2joao", titulo: "2 João" },
  { nome: "3joao", titulo: "3 João" },
  { nome: "judas", titulo: "Judas" },
  { nome: "apocalipse", titulo: "Apocalipse" }
];
