export const velhoTestamento = [
  { id: 1, nome: 'gn', titulo: 'Gênesis', capitulos: 50 },
  { id: 2, nome: 'ex', titulo: 'Êxodo', capitulos: 40 },
  { id: 3, nome: 'lv', titulo: 'Levítico', capitulos: 27 },
  { id: 4, nome: 'nm', titulo: 'Números', capitulos: 36 },
  { id: 5, nome: 'dt', titulo: 'Deuteronômio', capitulos: 34 },
  { id: 6, nome: 'js', titulo: 'Josué', capitulos: 24 },
  { id: 7, nome: 'jz', titulo: 'Juízes', capitulos: 21 },
  { id: 8, nome: 'rt', titulo: 'Rute', capitulos: 4 },
  { id: 9, nome: '1sm', titulo: '1 Samuel', capitulos: 31 },
  { id: 10, nome: '2sm', titulo: '2 Samuel', capitulos: 24 },
  { id: 11, nome: '1rs', titulo: '1 Reis', capitulos: 22 },
  { id: 12, nome: '2rs', titulo: '2 Reis', capitulos: 25 },
  { id: 13, nome: '1cr', titulo: '1 Crônicas', capitulos: 29 },
  { id: 14, nome: '2cr', titulo: '2 Crônicas', capitulos: 36 },
  { id: 15, nome: 'ed', titulo: 'Esdras', capitulos: 10 },
  { id: 16, nome: 'ne', titulo: 'Neemias', capitulos: 13 },
  { id: 17, nome: 'et', titulo: 'Ester', capitulos: 10 },
  { id: 18, nome: 'jó', titulo: 'Jó', capitulos: 42 },
  { id: 19, nome: 'sl', titulo: 'Salmos', capitulos: 150 },
  { id: 20, nome: 'pv', titulo: 'Provérbios', capitulos: 31 },
  { id: 21, nome: 'ec', titulo: 'Eclesiastes', capitulos: 12 },
  { id: 22, nome: 'ct', titulo: 'Cânticos', capitulos: 8 },
  { id: 23, nome: 'is', titulo: 'Isaías', capitulos: 66 },
  { id: 24, nome: 'jr', titulo: 'Jeremias', capitulos: 52 },
  { id: 25, nome: 'lm', titulo: 'Lamentações', capitulos: 5 },
  { id: 26, nome: 'ez', titulo: 'Ezequiel', capitulos: 48 },
  { id: 27, nome: 'dn', titulo: 'Daniel', capitulos: 12 },
  { id: 28, nome: 'os', titulo: 'Oséias', capitulos: 14 },
  { id: 29, nome: 'jl', titulo: 'Joel', capitulos: 3 },
  { id: 30, nome: 'am', titulo: 'Amós', capitulos: 9 },
  { id: 31, nome: 'ob', titulo: 'Obadias', capitulos: 1 },
  { id: 32, nome: 'jn', titulo: 'Jonas', capitulos: 4 },
  { id: 33, nome: 'mq', titulo: 'Miqueias', capitulos: 7 },
  { id: 34, nome: 'na', titulo: 'Naum', capitulos: 3 },
  { id: 35, nome: 'hc', titulo: 'Habacuque', capitulos: 3 },
  { id: 36, nome: 'sf', titulo: 'Sofonias', capitulos: 3 },
  { id: 37, nome: 'ag', titulo: 'Ageu', capitulos: 2 },
  { id: 38, nome: 'zc', titulo: 'Zacarias', capitulos: 14 },
  { id: 39, nome: 'ml', titulo: 'Malaquias', capitulos: 4 },
];

export const novoTestamento = [
  { id: 40, nome: 'mt', titulo: 'Mateus', capitulos: 28 },
  { id: 41, nome: 'mc', titulo: 'Marcos', capitulos: 16 },
  { id: 42, nome: 'lc', titulo: 'Lucas', capitulos: 24 },
  { id: 43, nome: 'jo', titulo: 'João', capitulos: 21 },
  { id: 44, nome: 'atos', titulo: 'Atos', capitulos: 28 },
  { id: 45, nome: 'rm', titulo: 'Romanos', capitulos: 16 },
  { id: 46, nome: '1co', titulo: '1 Coríntios', capitulos: 16 },
  { id: 47, nome: '2co', titulo: '2 Coríntios', capitulos: 13 },
  { id: 48, nome: 'gl', titulo: 'Gálatas', capitulos: 6 },
  { id: 49, nome: 'ef', titulo: 'Efésios', capitulos: 6 },
  { id: 50, nome: 'fp', titulo: 'Filipenses', capitulos: 4 },
  { id: 51, nome: 'cl', titulo: 'Colossenses', capitulos: 4 },
  { id: 52, nome: '1ts', titulo: '1 Tessalonicenses', capitulos: 5 },
  { id: 53, nome: '2ts', titulo: '2 Tessalonicenses', capitulos: 3 },
  { id: 54, nome: '1tm', titulo: '1 Timóteo', capitulos: 6 },
  { id: 55, nome: '2tm', titulo: '2 Timóteo', capitulos: 4 },
  { id: 56, nome: 'tt', titulo: 'Tito', capitulos: 3 },
  { id: 57, nome: 'fm', titulo: 'Filemom', capitulos: 1 },
  { id: 58, nome: 'hb', titulo: 'Hebreus', capitulos: 13 },
  { id: 59, nome: 'tg', titulo: 'Tiago', capitulos: 5 },
  { id: 60, nome: '1pe', titulo: '1 Pedro', capitulos: 5 },
  { id: 61, nome: '2pe', titulo: '2 Pedro', capitulos: 3 },
  { id: 62, nome: '1jo', titulo: '1 João', capitulos: 5 },
  { id: 63, nome: '2jo', titulo: '2 João', capitulos: 1 },
  { id: 64, nome: '3jo', titulo: '3 João', capitulos: 1 },
  { id: 65, nome: 'jd', titulo: 'Judas', capitulos: 1 },
  { id: 66, nome: 'ap', titulo: 'Apocalipse', capitulos: 22 },
];

export const livros = [
  { id: 1, nome: 'gn', titulo: 'Gênesis', capitulos: 50 },
  { id: 2, nome: 'ex', titulo: 'Êxodo', capitulos: 40 },
  { id: 3, nome: 'lv', titulo: 'Levítico', capitulos: 27 },
  { id: 4, nome: 'nm', titulo: 'Números', capitulos: 36 },
  { id: 5, nome: 'dt', titulo: 'Deuteronômio', capitulos: 34 },
  { id: 6, nome: 'js', titulo: 'Josué', capitulos: 24 },
  { id: 7, nome: 'jz', titulo: 'Juízes', capitulos: 21 },
  { id: 8, nome: 'rt', titulo: 'Rute', capitulos: 4 },
  { id: 9, nome: '1sm', titulo: '1 Samuel', capitulos: 31 },
  { id: 10, nome: '2sm', titulo: '2 Samuel', capitulos: 24 },
  { id: 11, nome: '1rs', titulo: '1 Reis', capitulos: 22 },
  { id: 12, nome: '2rs', titulo: '2 Reis', capitulos: 25 },
  { id: 13, nome: '1cr', titulo: '1 Crônicas', capitulos: 29 },
  { id: 14, nome: '2cr', titulo: '2 Crônicas', capitulos: 36 },
  { id: 15, nome: 'ed', titulo: 'Esdras', capitulos: 10 },
  { id: 16, nome: 'ne', titulo: 'Neemias', capitulos: 13 },
  { id: 17, nome: 'et', titulo: 'Ester', capitulos: 10 },
  { id: 18, nome: 'jó', titulo: 'Jó', capitulos: 42 },
  { id: 19, nome: 'sl', titulo: 'Salmos', capitulos: 150 },
  { id: 20, nome: 'pv', titulo: 'Provérbios', capitulos: 31 },
  { id: 21, nome: 'ec', titulo: 'Eclesiastes', capitulos: 12 },
  { id: 22, nome: 'ct', titulo: 'Cânticos', capitulos: 8 },
  { id: 23, nome: 'is', titulo: 'Isaías', capitulos: 66 },
  { id: 24, nome: 'jr', titulo: 'Jeremias', capitulos: 52 },
  { id: 25, nome: 'lm', titulo: 'Lamentações', capitulos: 5 },
  { id: 26, nome: 'ez', titulo: 'Ezequiel', capitulos: 48 },
  { id: 27, nome: 'dn', titulo: 'Daniel', capitulos: 12 },
  { id: 28, nome: 'os', titulo: 'Oséias', capitulos: 14 },
  { id: 29, nome: 'jl', titulo: 'Joel', capitulos: 3 },
  { id: 30, nome: 'am', titulo: 'Amós', capitulos: 9 },
  { id: 31, nome: 'ob', titulo: 'Obadias', capitulos: 1 },
  { id: 32, nome: 'jn', titulo: 'Jonas', capitulos: 4 },
  { id: 33, nome: 'mq', titulo: 'Miqueias', capitulos: 7 },
  { id: 34, nome: 'na', titulo: 'Naum', capitulos: 3 },
  { id: 35, nome: 'hc', titulo: 'Habacuque', capitulos: 3 },
  { id: 36, nome: 'sf', titulo: 'Sofonias', capitulos: 3 },
  { id: 37, nome: 'ag', titulo: 'Ageu', capitulos: 2 },
  { id: 38, nome: 'zc', titulo: 'Zacarias', capitulos: 14 },
  { id: 39, nome: 'ml', titulo: 'Malaquias', capitulos: 4 },
  { id: 40, nome: 'mt', titulo: 'Mateus', capitulos: 28 },
  { id: 41, nome: 'mc', titulo: 'Marcos', capitulos: 16 },
  { id: 42, nome: 'lc', titulo: 'Lucas', capitulos: 24 },
  { id: 43, nome: 'jo', titulo: 'João', capitulos: 21 },
  { id: 44, nome: 'atos', titulo: 'Atos', capitulos: 28 },
  { id: 45, nome: 'rm', titulo: 'Romanos', capitulos: 16 },
  { id: 46, nome: '1co', titulo: '1 Coríntios', capitulos: 16 },
  { id: 47, nome: '2co', titulo: '2 Coríntios', capitulos: 13 },
  { id: 48, nome: 'gl', titulo: 'Gálatas', capitulos: 6 },
  { id: 49, nome: 'ef', titulo: 'Efésios', capitulos: 6 },
  { id: 50, nome: 'fp', titulo: 'Filipenses', capitulos: 4 },
  { id: 51, nome: 'cl', titulo: 'Colossenses', capitulos: 4 },
  { id: 52, nome: '1ts', titulo: '1 Tessalonicenses', capitulos: 5 },
  { id: 53, nome: '2ts', titulo: '2 Tessalonicenses', capitulos: 3 },
  { id: 54, nome: '1tm', titulo: '1 Timóteo', capitulos: 6 },
  { id: 55, nome: '2tm', titulo: '2 Timóteo', capitulos: 4 },
  { id: 56, nome: 'tt', titulo: 'Tito', capitulos: 3 },
  { id: 57, nome: 'fm', titulo: 'Filemom', capitulos: 1 },
  { id: 58, nome: 'hb', titulo: 'Hebreus', capitulos: 13 },
  { id: 59, nome: 'tg', titulo: 'Tiago', capitulos: 5 },
  { id: 60, nome: '1pe', titulo: '1 Pedro', capitulos: 5 },
  { id: 61, nome: '2pe', titulo: '2 Pedro', capitulos: 3 },
  { id: 62, nome: '1jo', titulo: '1 João', capitulos: 5 },
  { id: 63, nome: '2jo', titulo: '2 João', capitulos: 1 },
  { id: 64, nome: '3jo', titulo: '3 João', capitulos: 1 },
  { id: 65, nome: 'jd', titulo: 'Judas', capitulos: 1 },
  { id: 66, nome: 'ap', titulo: 'Apocalipse', capitulos: 22 },
];
